language: c

dist: xenial

compiler:
    - gcc

before_install:
    - sudo apt-get install -y libgc-dev libcmocka-dev

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make && make test

